name: rumah_sampah_t_a
version: 1.0.0+1
publish_to: none
description: Aplikaksi rumah sampah by Ilma Faridah Hannun
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  charts_flutter: ^0.12.0
  cloud_firestore: 4.5.0
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.6
  email_auth: ^1.0.0
  email_otp: ^2.0.1
  file_picker: ^5.3.0
  firebase_app_check: ^0.1.2+1
  firebase_auth: 4.4.0
  firebase_core: 2.9.0
  firebase_storage: 11.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^4.0.0
  flutter_native_splash: ^2.2.19
  flutter_svg: ^2.0.5
  # geocoder: ^0.2.1
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: 4.6.5
  google_maps_flutter: ^2.2.8
  google_maps_place_picker_mb: ^3.0.2
  http: ^0.13.6
  image_picker: ^0.8.7+5
  intl: ^0.17.0
  json_serializable: ^6.6.2
  latlong2: ^0.8.2
  location: ^4.4.0
  path: ^1.8.2
  searchable_paginated_dropdown: ^1.2.0
  shared_preferences: ^2.1.1
  trust_location: ^2.0.13
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  #color: "#ffffff"
  background_image: assets/image/SplashScreen.png
  android: true
  fullscreen: true
  ndroid_gravity: center

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
    - family: RockSalt
      fonts:
        - asset: assets/fonts/RockSalt-Regular.ttf
